# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20160606_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='up',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vms',
            name='run',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
