# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_auto_20160606_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='CPU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vms',
            name='Guest',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='vms',
            name='Ipa',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='vms',
            name='Mem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vms',
            name='run',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
