# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_text', models.CharField(max_length=20)),
                ('IP_addr', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_text', models.CharField(max_length=200)),
                ('moid', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.server')),
            ],
        ),
    ]
